# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Flight BK 
tagline:          'A Flight Booking App'
description:      'A mock flight booking app that is catered towards working adults looking to book a flight cheaply.'
url:              https://GiddyGit.github.io
baseurl:          /

author:
  name:           'Amelia Kobayashi'
  url:            https://www.instagram.com/a_b_k321/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
